use eval_gettext() instead of $"" [functions]

diff --git a/functions/apkdump b/functions/apkdump
--- a/functions/apkdump
+++ b/functions/apkdump
@@ -10,10 +10,13 @@
 #########################################################
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
-if ! which aapt &>/dev/null; then
-	echo -e $"aapt not found, apkdump won't work."
+dep="aapt"
+prog="apkdump"
+
+if ! which ${dep} &>/dev/null; then
+	echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 	exit 1
 fi
 
@@ -39,11 +42,12 @@ case ${opt} in
 
 	*)
 		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
-			-l "GNU GPL v3" -n "apkdump" -s $"grab apk infos using aapt" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-			-o $"name:apk|get package name of apk"\
-			-o $"version:apk|get human-readable version of apk"\
-			-o $"versioncode:apk|get version code of apk"\
-			-o $"perms:apk|get list of requested permissions"
+			-l "GNU GPL v3" -n "apkdump" -s "$(eval_gettext "grab apk infos using aapt")" \
+			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
+			-o "$(eval_gettext "name:apk|get package name of apk")"\
+			-o "$(eval_gettext "version:apk|get human-readable version of apk")"\
+			-o "$(eval_gettext "versioncode:apk|get version code of apk")"\
+			-o "$(eval_gettext "perms:apk|get list of requested permissions")"
 	;;
 esac
 
diff --git a/functions/check b/functions/check
--- a/functions/check
+++ b/functions/check
@@ -10,7 +10,7 @@
 #########################################################
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
 is_number () {
 	[[ ${1} =~ ^[+-]?[0-9]+([.,][0-9]+)?$ || \
@@ -103,11 +103,11 @@ is_mail () {
 	local status=0
 
 	if ! is_valid_address "${address}"; then
-		echo $"invalid address \"${address}\""
+		echo "$(eval_gettext "invalid address: ${address}")"
 		status=1
 	else
 		if ! is_valid_domain "${domain}"; then
-			echo $"domain \"${domain}\" unreachable"
+			echo "$(eval_gettext "domain: ${domain} unreachable")"
 			status=1
 		fi
 	fi
@@ -132,8 +132,10 @@ case ${1} in
 	bf)	is_false "${2}"			;;
 
 	m)
-		if ! which dig &>/dev/null; then
-			echo -e $"dig not found, 'check m' won't work."
+		dep="dig"
+		prog="'check m'"
+		if ! which ${dep} &>/dev/null; then
+			echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 			exit 1
 		fi
 
@@ -142,22 +144,23 @@ case ${1} in
 
 	*)
 		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
-				-l "GNU GPL v3" -n "check" -s $"additional test functions" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-				-o $"n:4 [4[,.]4|check if arg is any number"\
-				-o $"i:4|check if arg is integer"\
-				-o $"f:4[,.]4|check if arg is float"\
-				-o $"h:301DE8|check if arg is hex"\
-				-o $"o:24|check if arg is octal"\
-				-o $"hc:[#]FFFFFF|check if arg is valid hex color"\
-				-o $"s:test|check if arg is a string"\
-				-o $"p:+|check if arg is special character"\
-				-o $"c:testabc abc|check if arg1 contains arg2"\
-				-o $"sw:testabc t|check if arg1 starts with arg2"\
-				-o $"ew:14235 235|check if arg1 ends with arg2"\
-				-o $"b:\${VAR}|check if arg is a boolean"\
-				-o $"bt:\${VAR}|check if arg is boolean true"\
-				-o $"bf:\${VAR}|check if arg is boolean false"\
-				-o $"m:test@dom.tld|check if arg is valid mail address"
+				-l "GNU GPL v3" -n "check" -s "$(eval_gettext "additional test functions")"\
+				-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
+				-o "$(eval_gettext "n:4 [4[,.]4|check if arg is any number")"\
+				-o "$(eval_gettext "i:4|check if arg is integer")"\
+				-o "$(eval_gettext "f:4[,.]4|check if arg is float")"\
+				-o "$(eval_gettext "h:301DE8|check if arg is hex")"\
+				-o "$(eval_gettext "o:24|check if arg is octal")"\
+				-o "$(eval_gettext "hc:[#]FFFFFF|check if arg is valid hex color")"\
+				-o "$(eval_gettext "s:test|check if arg is a string")"\
+				-o "$(eval_gettext "p:+|check if arg is special character")"\
+				-o "$(eval_gettext "c:testabc abc|check if arg1 contains arg2")"\
+				-o "$(eval_gettext "sw:testabc t|check if arg1 starts with arg2")"\
+				-o "$(eval_gettext "ew:14235 235|check if arg1 ends with arg2")"\
+				-o "$(eval_gettext "b:\${VAR}|check if arg is a boolean")"\
+				-o "$(eval_gettext "bt:\${VAR}|check if arg is boolean true")"\
+				-o "$(eval_gettext "bf:\${VAR}|check if arg is boolean false")"\
+				-o "$(eval_gettext "m:test@dom.tld|check if arg is valid mail address")"
 	;;
 esac
 
diff --git a/functions/gitkit b/functions/gitkit
--- a/functions/gitkit
+++ b/functions/gitkit
@@ -10,12 +10,14 @@
 #########################################################
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
 gitkit_ssh_add () {
 	if check bt $(bashstyle --ini-get git_ssh_remember); then
-		if ! which ssh-add &>/dev/null; then
-			echo -e $"ssh-add not found, remembering password won't work."
+		local dep="ssh-add"
+		local prog="remembering SSH password"
+		if ! which ${dep} &>/dev/null; then
+			echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 			exit 1
 		fi
 
@@ -27,22 +29,28 @@ gitkit_ssh_add () {
 		eval git_ssh_keyfile=$(bashstyle --ini-get git_ssh_keyfile)
 
 		if test ${gitkit_time} -eq 0 -o ${gitkit_time} -le $(($(date +%s) - ${git_ssh_timeout})); then
-			echo -e $"\n${egreen}[0] ssh-add ${git_ssh_keyfile}\n"
+			echo -e "$(eval_gettext "\n${egreen}[0] ssh-add ${git_ssh_keyfile}\n")"
 			ssh-add "${git_ssh_keyfile}" && echo $(date +%s) > ${gitkit_file}
 		fi
 	fi
 }
 
 github_clone () {
-	if ! which wget &>/dev/null; then
-			echo -e $"wget not found, 'gitkit cloneorg' won't work."
+	local dep="wget"
+	local prog="'gitkit cloneorg'"
+
+	if ! which ${dep} &>/dev/null; then
+			echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 			exit 1
 	fi
 
-	if ! which xe &>/dev/null; then
-		echo -e $"xe not found, 'gitkit cloneorg' won't work."
+	dep="xe"
+
+	if ! which ${dep} &>/dev/null; then
+		echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 		exit 1
 	fi
+
 	wget -qO - https://api.github.com/"${1}"/"${2}"/repos?per_page=200 | \
 		awk -F\" '/ssh_url/{print $4}' | xe git clone
 }
@@ -83,21 +91,21 @@ case ${1} in
 	bz2)
 		if [[ -d .git ]]; then
 			git archive master | bzip2 -9 > "$(basename "${PWD}")".tar.bz2
-		else	echo $"current directory is not the root of a git repository"
+		else	echo "$(eval_gettext "current directory is not the root of a git repository")"
 		fi
 	;;
 
 	xz)
 		if [[ -d .git ]]; then
 			git archive master | xz -9 > "$(basename "${PWD}")".tar.xz
-		else	echo $"current directory is not the root of a git repository"
+		else	echo "$(eval_gettext "current directory is not the root of a git repository")"
 		fi
 	;;
 
 	zip)
 		if [[ -d .git ]]; then
 			git archive master --format=zip > "$(basename "${PWD}")".zip
-		else	echo $"current directory is not the root of a git repository"
+		else	echo "$(eval_gettext "current directory is not the root of a git repository")"
 		fi
 	;;
 
@@ -114,10 +122,14 @@ case ${1} in
 	;;
 
 	funmsg)
-		if ! which wget &>/dev/null; then
-			echo -e $"wget not found, 'gitkit funmsg' won't work."
-			exit 1
+		dep="wget"
+		prog="'gitkit funmsg'"
+
+		if ! which ${dep} &>/dev/null; then
+				echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
+				exit 1
 		fi
+
 		wget -qO - http://whatthecommit.com/index.txt
 	;;
 
@@ -135,10 +147,10 @@ case ${1} in
 				;;
 
 				* )
-					echo $"couldn't parse web location"
+					echo "$(eval_gettext "couldn't parse web location")"
 				;;
 			esac
-		else	echo $"current directory is not the root of a git repository"
+		else	echo "$(eval_gettext "current directory is not the root of a git repository")"
 		fi
 	;;
 
@@ -162,23 +174,23 @@ case ${1} in
 	undelete)
 		if [ -d .git ]; then
 			git checkout "$(git ls-files --deleted)"
-		else	echo $"current directory is not the root of a git repository"
+		else	echo "$(eval_gettext "current directory is not the root of a git repository")"
 		fi
 	;;
 
 	push)
 		gitkit_ssh_add
 
-		echo -e $"\n${eblue}[1] push to upstream\n"
+		echo -e "$(eval_gettext "\n${eblue}[1] push to upstream\n")"
 		git push
 
-		echo -e $"\n${ecyan}[2] push tags to upstream\n"
+		echo -e "$(eval_gettext "\n${ecyan}[2] push tags to upstream\n")"
 		git push --tag
 
 		if [ -f ${PWD}/.git_mirror ]; then
-			echo -e $"\n${emagenta}[3] push to mirror\n"
+			echo -e "$(eval_gettext "\n${emagenta}[3] push to mirror\n")"
 			for repo in $(cat ${PWD}/.git_mirror); do
-				echo -e $"${eyellow} * mirror: ${repo}\n"
+				echo -e "$(eval_gettext "${eyellow} * mirror: ${repo}\n")"
 				git push --mirror "${repo}"
 			done
 		fi
@@ -186,32 +198,34 @@ case ${1} in
 
 	taga)
 		shift
+		local tag=${1}
 
-		if [ ! -z "$(git tag -l "${1}")" ]; then
-			echo $"tag \"${1}\" already exists!"
+		if [ ! -z "$(git tag -l "${tag}")" ]; then
+			echo "$(eval_gettext "tag ${tag} already exists!")"
 		else
 			gitkit_ssh_add
 
-			echo -e $"\n${eblue}[1] create local tag ${1}\n"
+			echo -e "$(eval_gettext "\n${eblue}[1] create local tag ${tag}\n")"
 			git tag -a "${@}" || exit 1
 
-			echo -e $"\n${ecyan}[2] push tag to remote\n"
+			echo -e "$(eval_gettext "\n${ecyan}[2] push tag to remote\n")"
 			git push --tag
 		fi
 	;;
 
 	tagd)
 		shift
+		local tag=${1}
 
 		if [ -z "$(git tag -l "${1}")" ]; then
-			echo $"tag \"${1}\" does not exist!"
+			echo "$(eval_gettext "tag ${tag} does not exist!")"
 		else
 			gitkit_ssh_add
 
-			echo -e $"\n${eblue}[1] remove local tag ${1}\n"
+			echo -e "$(eval_gettext "\n${eblue}[1] remove local tag ${tag}\n")"
 			git tag -d "${1}" || exit 1
 
-			echo -e $"\n${ecyan}[2] remove remote tag\n"
+			echo -e "$(eval_gettext "\n${ecyan}[2] remove remote tag\n")"
 			git push origin :refs/tags/"${1}"
 		fi
 	;;
@@ -222,12 +236,12 @@ case ${1} in
 		out_TAG="${2}"
 
 		if [ -z "$(git tag -l "${in_TAG}")" ]; then
-			echo $"tag \"${in_TAG}\" does not exist!"
+			echo "$(eval_gettext "tag ${in_TAG} does not exist!")"
 			exit 1
 		fi
 
 		if [ ! -z "$(git tag -l "${out_TAG}")" ]; then
-			echo $"tag \"${out_TAG}\" already exists!"
+			echo "$(eval_gettext "tag ${out_TAG} already exists!")"
 			exit 1
 		fi
 
@@ -244,12 +258,12 @@ case ${1} in
 		COM="${2}"
 
 		if [ -z "$(git tag -l "${TAG}")" ]; then
-			echo $"tag \"${TAG}\" does not exist!"
+			echo "$(eval_gettext "tag ${TAG} does not exist!")"
 			exit 1
 		fi
 
 		if [ ! "$(git rev-parse "${COM}")" ]; then
-			echo $"commit \"${COM}\" does not exist!"
+			echo "$(eval_gettext "commit ${COM} does not exist!")"
 			exit 1
 		fi
 
@@ -261,25 +275,25 @@ case ${1} in
 
 	*)
 		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
-			-l "GNU GPL v3" -n "gitkit" -s $"various companion functions for Git" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-			-o $"action:|print the current action in a Git repo"\
-			-o $"branch:|print the current branch in a Git repo"\
-			-o $"bz2:|create bz2 archive from a Git repo"\
-			-o $"xz:|create xz archive from a Git repo"\
-			-o $"zip:|create zip archive from a Git repo"\
-			-o $"cloneuser:username|clone all repos from a GitHub user (SSH)"\
-			-o $"cloneorg:organization|clone all repos from a GitHub organization (SSH)"\
-			-o $"export:directory|export Git repo for release tarball"\
-			-o $"funmsg:|create funny Git commit message"\
-			-o $"web:|open project page using x-www-browser"\
-			-o $"revision:|get 6 digit revision from a Git repo"\
-			-o $"revno:|get traditional revision number from a Git repo"\
-			-o $"undelete:|undelete files accidentally deleted locally"\
-			-o $"push:|push/push tag upstream + push to mirror in one go"\
-			-o $"taga:tag [-m msg commit]|create a tag and push remote"\
-			-o $"tagd:tag|remove tag locally and remote"\
-			-o $"tagr:tag newtag|rename a tag locally and remote"\
-			-o $"tagc:tag newcommit|make tag point to different commit"
+			-l "GNU GPL v3" -n "gitkit" -s "$(eval_gettext "various companion functions for Git")"\
+			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
+			-o "$(eval_gettext "action:|print the current action in a Git repo")"\
+			-o "$(eval_gettext "branch:|print the current branch in a Git repo")"\
+			-o "$(eval_gettext "bz2:|create bz2 archive from a Git repo")"\
+			-o "$(eval_gettext "xz:|create xz archive from a Git repo")"\
+			-o "$(eval_gettext "zip:|create zip archive from a Git repo")"\
+			-o "$(eval_gettext "cloneuser:username|clone all repos from a GitHub user (SSH)")"\
+			-o "$(eval_gettext "cloneorg:organization|clone all repos from a GitHub organization (SSH)")"\
+			-o "$(eval_gettext "export:directory|export Git repo for release tarball")"\
+			-o "$(eval_gettext "funmsg:|create funny Git commit message")"\
+			-o "$(eval_gettext "web:|open project page using x-www-browser")"\
+			-o "$(eval_gettext "revision:|get 6 digit revision from a Git repo")"\
+			-o "$(eval_gettext "revno:|get traditional revision number from a Git repo")"\
+			-o "$(eval_gettext "undelete:|undelete files accidentally deleted locally")"\
+			-o "$(eval_gettext "push:|push/push tag upstream + push to mirror in one go")"\
+			-o "$(eval_gettext "taga:tag [-m msg commit]|create a tag and push remote")"\
+			-o "$(eval_gettext "tagd:tag|remove tag locally and remote")"\
+			-o "$(eval_gettext "tagr:tag newtag|rename a tag locally and remote")"\
+			-o "$(eval_gettext "tagc:tag newcommit|make tag point to different commit")"
 	;;
 esac
-
diff --git a/functions/man2pdf b/functions/man2pdf
--- a/functions/man2pdf
+++ b/functions/man2pdf
@@ -10,22 +10,39 @@
 #########################################################
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
-if ! which ps2pdf &>/dev/null; then
-	echo -e $"ps2pdf not found, man2pdf won't work."
+dep="ps2pdf"
+prog="man2pdf"
+
+if ! which ${dep} &>/dev/null; then
+	echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 	exit 1
 fi
+
+man_exists () {
+	man -t "${1}" &>/dev/null
+
+	# 'man' returns 16, if a manpage does not exist
+	if [[ $? -ne 0 ]]; then
+		return 1
+	else	return 0
+	fi
+}
 
 case ${1} in
 	--help | -h | "")
 		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
-			-l "GNU GPL v3" -n "man2pdf" -s $"create PDF from a manpage" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-			-o $"manpage:bash|manpage to create a PDF from"
+			-l "GNU GPL v3" -n "man2pdf" -s "$(eval_gettext "create PDF from a manpage")"\
+			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
+			-o "$(eval_gettext "manpage:bash|manpage to create a PDF from")"
 	;;
 
 	* )
-		man -t "${1}" | ps2pdf - >"${1}.pdf" || echo $"manpage ${1} does not exist"
+		manpage="${1}"
+
+		man_exists "${manpage}" && man -t "${manpage}" | ps2pdf - > "${manpage}.pdf" \
+			|| echo "$(eval_gettext "manpage ${manpage} does not exist")"
 	;;
 esac
 
diff --git a/functions/map b/functions/map
--- a/functions/map
+++ b/functions/map
@@ -12,31 +12,30 @@
 # by downdiagonal
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
 case ${1} in
 	--help | -h | "")
 		bashstyle-help -a "downdiagonal" -e "" -h "http://www.commandlinefu.com/"\
-			-l "Public Domain" -n "map" -s $"run a command on given files or directories"\
+			-l "Public Domain" -n "map" -s "$(eval_gettext "run a command on given files or directories")"\
 			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-			-o $"command:|command to map"\
-			-o $" -- :|end of command"\
-			-o $"files:|list of files or directories"
+			-o "$(eval_gettext "command:|command to map")"\
+			-o "$(eval_gettext " -- :|end of command")"\
+			-o "$(eval_gettext "files:|list of files or directories")"
 	;;
 
 	* )
 		if [ $# -lt 2 ] || [[ ! "$*" =~ [[:space:]]--[[:space:]] ]];then
-			echo "Invalid syntax." >&2; exit 1
+			echo "$(eval_gettext "invalid syntax")" >&2; exit 1
 		fi
 
 		until [[ $1 =~ -- ]]; do
-			command="$command $1"; shift
+			command="$command ${1}"; shift
 		done
 
 		command="$command ${1%:}"; shift
-		for i in "$@"; do
+		for i in "${@}"; do
 			eval "${command//\\/\\\\} \"${i//\\/\\\\}\""
 		done
 	;;
 esac
-
diff --git a/functions/movie2gif b/functions/movie2gif
--- a/functions/movie2gif
+++ b/functions/movie2gif
@@ -10,10 +10,13 @@
 #########################################################
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
-if ! which ffmpeg &>/dev/null; then
-	echo $"ffmpeg not found, movie2gif won't work."
+dep="ffmpeg"
+prog="movie2gif"
+
+if ! which ${dep} &>/dev/null; then
+	echo "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 	exit 1
 fi
 
@@ -23,17 +26,16 @@ case ${1} in
 	--help | -h | "")
 		bashstyle-help -a "maxwux" -e "" -h "http://www.commandlinefu.com/"\
 				-l "Public Domain" -n "movie2gif"\
-				-s $"create GIF from Movie"\
+				-s "$(eval_gettext "create GIF from Movie")"\
 				-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-				-o $"input file:coolfilm.avi|movie file to generate GIF from"\
-				-o $"start time:00:00:00.000|start time"\
-				-o $"duration:10|scene duration"\
-				-o $"scale:320:-1|GIF scale"\
-				-o $"output file:coolgif.gif|output file name"
+				-o "$(eval_gettext "input file:coolfilm.avi|movie file to generate GIF from")"\
+				-o "$(eval_gettext "start time:00:00:00.000|start time")"\
+				-o "$(eval_gettext "duration:10|scene duration")"\
+				-o "$(eval_gettext "scale:320:-1|GIF scale")"\
+				-o "$(eval_gettext "output file:coolgif.gif|output file name")"
 	;;
 
 	* )
 		ffmpeg -ss "${2}" -t "${3}" -i "${1}" -vf scale="${4}" "${5}"
 	;;
 esac
-
diff --git a/functions/systemkit b/functions/systemkit
--- a/functions/systemkit
+++ b/functions/systemkit
@@ -10,13 +10,15 @@
 #########################################################
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
 case ${1} in
-
 	battery)
-		if ! which acpi &>/dev/null; then
-			echo -e $"acpi not found, 'systemkit battery' won't work."
+		dep="acpi"
+		prog="'systemkit battery'"
+
+		if ! which ${dep} &>/dev/null; then
+			echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 			exit 1
 		fi
 
@@ -56,8 +58,10 @@ case ${1} in
 	;;
 
 	externalip)
+		dep="wget"
+		prog="'systemkit externalip'"
 		if ! which wget &>/dev/null; then
-			echo -e $"wget not found, 'systemkit externalip' won't work."
+			echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 			exit 1
 		fi
 		wget -q -O - http://showip.spamt.net/
@@ -140,36 +144,42 @@ case ${1} in
 	;;
 
 	partitions)
-		echo -e $"Partitions:\n"\
-	$"device-node type mount used free total\n"\
+		echo -e "$(eval_gettext "Partitions:\n")"\
+	"$(eval_gettext "device-node type mount used free total\n")"\
 	"$(df -h --output=source,fstype,target,used,avail,size | grep "^/dev")\n" | column -t
 	;;
 
 	pci)
-		if ! which lspci &>/dev/null; then
-			echo -e $"lspci not found, 'systemkit pci' won't work."
+		dep="lspci"
+		prog="'systemkit pci'"
+		if ! which ${dep} &>/dev/null; then
+			echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 			exit 1
 		fi
-		echo -e $"PCI Devices:\n\n""$(lspci -vkmm)\n"
+		echo -e "$(eval_gettext "PCI Devices:\n\n")" "$(lspci -vkmm)\n"
 	;;
 
 	usb)
-		if ! which lsusb &>/dev/null; then
-			echo -e $"lsusb not found, 'systemkit usb' won't work."
+		dep="lsusb"
+		prog="'systemkit usb'"
+		if ! which ${dep} &>/dev/null; then
+			echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 			exit 1
 		fi
 		echo -e $"USB Devices:\n\n""$(lsusb -v)\n"
 	;;
 
 	bios)
-		if [[ ${EUID} == 0 ]]; then 
+		if [[ ${EUID} == 0 ]]; then
+			dep="dmidecode"
+			prog="'systemkit bios'"
 			if ! which dmidecode &>/dev/null; then
-				echo -e $"dmidecode not found, 'systemkit bios' won't work."
+				echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 				exit 1
 			fi
-			echo -e "SMBIOS/DMI Info:\n\n""$(dmidecode -q)\n"
+			echo -e "$(eval_gettext "SMBIOS/DMI Info:\n\n")" "$(dmidecode -q)\n"
 		else
-			echo -e $"You're not root"
+			echo -e "$(eval_gettext "You're not root")"
 			exit 1
 		fi
 	;;
@@ -265,44 +275,42 @@ case ${1} in
 
 	*)
 		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
-			-l "GNU GPL v3" -n "systemkit" -s $"show various system information" \
+			-l "GNU GPL v3" -n "systemkit" -s "$(eval_gettext "show various system information")"\
 			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-			-o $"battery:|show battery load state using acpi"\
-			-o $"cpuload:|show cpu load"\
-			-o $"externalip:|show your PCs external ip"\
-			-o $"internalip:interface|show interface's internal ip"\
-			-o $"usedram:|used RAM"\
-			-o $"usedram%:|used RAM in %"\
-			-o $"freeram:|free RAM"\
-			-o $"freeram%:|free RAM in %"\
-			-o $"totalram:|total RAM"\
-			-o $"dirsize:|size of all items in current dir"\
-			-o $"usedspace:mount|used space on mountpoint"\
-			-o $"freespace:mount|free space on mountpoint"\
-			-o $"totalspace:mount|total space on mountpoint"\
-			-o $"usedspace%:mount|used space on mountpoint in %"\
-			-o $"freespace%:mount|free space on mountpoint in %"\
-			-o $"cpu:|show cpu information"\
-			-o $"kernel:|show kernel information"\
-			-o $"partitons:|show mounted partitions information"\
-			-o $"pci:|show pci device information"\
-			-o $"usb:|show usb device information"\
-			-o $"bios:|show bios information [only root]"\
-			-o $"load1:|show load average for 1 minute"\
-			-o $"load5:|show load average for 5 minutes"\
-			-o $"load15:|show load average for 15 minutes"\
-			-o $"tty:|show current TTY device node"\
-			-o $"uptime:|show uptime in pretty printed format"\
-			-o $"cof:[directory]|count all files in directory (or pwd)"\
-			-o $"cod:[directory]|count all directories in directory (or pwd)"\
-			-o $"coi:[directory]|count all items in directory (or pwd)"\
-			-o $"cvf:[directory]|count visible files in directory (or pwd)"\
-			-o $"cvd:[directory]|count visible directories in directory (or pwd)"\
-			-o $"cvi:[directory]|count visible items in directory (or pwd)"\
-			-o $"chf:[directory]|count hidden files in directory (or pwd)"\
-			-o $"chd:[directory]|count hidden directories in directory (or pwd)"\
-			-o $"chi:[directory]|count hidden items in directory (or pwd)"
+			-o "$(eval_gettext "battery:|show battery load state using acpi")"\
+			-o "$(eval_gettext "cpuload:|show cpu load")"\
+			-o "$(eval_gettext "externalip:|show your PCs external ip")"\
+			-o "$(eval_gettext "internalip:interface|show interface's internal ip")"\
+			-o "$(eval_gettext "usedram:|used RAM")"\
+			-o "$(eval_gettext "usedram%:|used RAM in %")"\
+			-o "$(eval_gettext "freeram:|free RAM")"\
+			-o "$(eval_gettext "freeram%:|free RAM in %")"\
+			-o "$(eval_gettext "totalram:|total RAM")"\
+			-o "$(eval_gettext "dirsize:|size of all items in current dir")"\
+			-o "$(eval_gettext "usedspace:mount|used space on mountpoint")"\
+			-o "$(eval_gettext "freespace:mount|free space on mountpoint")"\
+			-o "$(eval_gettext "totalspace:mount|total space on mountpoint")"\
+			-o "$(eval_gettext "usedspace%:mount|used space on mountpoint in %")"\
+			-o "$(eval_gettext "freespace%:mount|free space on mountpoint in %")"\
+			-o "$(eval_gettext "cpu:|show cpu information")"\
+			-o "$(eval_gettext "kernel:|show kernel information")"\
+			-o "$(eval_gettext "partitons:|show mounted partitions information")"\
+			-o "$(eval_gettext "pci:|show pci device information")"\
+			-o "$(eval_gettext "usb:|show usb device information")"\
+			-o "$(eval_gettext "bios:|show bios information [only root]")"\
+			-o "$(eval_gettext "load1:|show load average for 1 minute")"\
+			-o "$(eval_gettext "load5:|show load average for 5 minutes")"\
+			-o "$(eval_gettext "load15:|show load average for 15 minutes")"\
+			-o "$(eval_gettext "tty:|show current TTY device node")"\
+			-o "$(eval_gettext "uptime:|show uptime in pretty printed format")"\
+			-o "$(eval_gettext "cof:directory|count all files in directory (or pwd)")"\
+			-o "$(eval_gettext "cod:directory|count all directories in directory (or pwd)")"\
+			-o "$(eval_gettext "coi:directory|count all items in directory (or pwd)")"\
+			-o "$(eval_gettext "cvf:directory|count visible files in directory (or pwd)")"\
+			-o "$(eval_gettext "cvd:directory|count visible directories in directory (or pwd)")"\
+			-o "$(eval_gettext "cvi:directory|count visible items in directory (or pwd)")"\
+			-o "$(eval_gettext "chf:directory|count hidden files in directory (or pwd)")"\
+			-o "$(eval_gettext "chd:directory|count hidden directories in directory (or pwd)")"\
+			-o "$(eval_gettext "chi:directory|count hidden items in directory (or pwd)")"
 	;;
-
 esac
-
diff --git a/functions/xmlpager b/functions/xmlpager
--- a/functions/xmlpager
+++ b/functions/xmlpager
@@ -10,20 +10,21 @@
 #########################################################
 
 . gettext.sh
-TEXTDOMAIN="bashstyle-rc"
+export TEXTDOMAIN="bashstyle-rc"
 
-if ! which xmlindent &>/dev/null; then
-	echo -e $"xmlindent not found, xmlpager won't work."
+dep="xmlindent"
+prog="xmlpager"
+if ! which ${dep} &>/dev/null; then
+	echo -e "$(eval_gettext "${dep} not found, ${prog} won't work.")"
 	exit 1
 fi
 
 case ${1} in
-
 	-h | --help )
 		bashstyle-help -a "hackerb9" -e "" -h "http://www.commandlinefu.com/"\
-			-l "GNU GPL v3" -n "xmlpager" -s $"pager for xml files with highlighted text"\
+			-l "GNU GPL v3" -n "xmlpager" -s "$(eval_gettext "pager for xml files with highlighted text")"\
 			-v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-			-o $"file:|xml file to read"
+			-o "$(eval_gettext "file:|xml file to read")"
 	;;
 
 	*)
@@ -31,6 +32,4 @@ case ${1} in
 			awk '{gsub(">",">'$(tput bold; tput setf 4)'"); gsub("<","'$(tput sgr0)'<"); print;} END {print "'$(tput sgr0)'"}' | \
 			less -r
 	;;
-
 esac
-
