check: guard 'm' for missing 'dig'

diff --git a/functions/check b/functions/check
--- a/functions/check
+++ b/functions/check
@@ -127,7 +127,15 @@ case ${1} in
 	b)	is_bool "${2}"			;;
 	bt)	is_true "${2}"			;;
 	bf)	is_false "${2}"			;;
-	m)	is_mail "${2}"			;;
+
+	m)
+		if ! which dig &>/dev/null; then
+			echo -e "dig not found, 'check m' won't work."
+			exit 1
+		fi
+
+		is_mail "${2}"
+	;;
 
 	*)
 		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
