prepare functions to be translated

diff --git a/functions/man2pdf b/functions/man2pdf
--- a/functions/man2pdf
+++ b/functions/man2pdf
@@ -9,21 +9,24 @@
 #							#
 #########################################################
 
+. gettext.sh
+TEXTDOMAIN="bashstyle-rc"
+
 if ! which ps2pdf &>/dev/null; then
-	echo -e "ps2pdf not found, man2pdf won't work."
+	echo -e $"ps2pdf not found, man2pdf won't work."
 	exit 1
 fi
 
 case ${1} in
-
 	--help | -h | "")
 		bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
-			-l "GNU GPL v3" -n "man2pdf" -s "create PDF from a manpage" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-			-o "manpage:bash|manpage to create a PDF from"
+			-l "GNU GPL v3" -n "man2pdf" -s $"create PDF from a manpage" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
+			-o $"manpage:bash|manpage to create a PDF from"
 	;;
 
 	* )
-		man -t "${1}" | ps2pdf - >"${1}.pdf" || echo "manpage ${1} does not exist"
+		man -t "${1}" | ps2pdf - >"${1}.pdf" || echo $"manpage ${1} does not exist"
 	;;
-
 esac
+
+unset TEXTDOMAIN
diff --git a/functions/randomfile b/functions/randomfile
--- a/functions/randomfile
+++ b/functions/randomfile
@@ -9,12 +9,15 @@
 #							#
 #########################################################
 
+. gettext.sh
+TEXTDOMAIN="bashstyle-rc"
+
 _randomfunc() {
 
 	command=""
 
 	if [ $# -lt 2 ] || [[ ! "$*" =~ [[:space:]]--[[:space:]] ]];then
-			echo "Invalid syntax." >&2; exit 1
+			echo $"Invalid syntax." >&2; exit 1
 	fi
 
 	if [[ "${1}" == "_zero_" ]]; then
@@ -52,28 +55,28 @@ _randomfunc() {
 
 _randomfile_help () {
 	bashstyle-help -a "Christopher Roy Bratusek" -e "nano@jpberlin.de" -h "https://www.nanolx.org/"\
-		-l "GNU GPL v3" -n "randomfile" -s "run a command on a random file" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
-		-o "command:|command to run for file"\
-		-o "--:|end of command"\
-		-o "files:|list of possible files"\
-		-o "\tor:|--"\
-		-o "-z command:|command to run for file, append result without space"\
-		-o "--:|end of command"\
-		-o "files:|list of possible files"\
-		-o "\tor:|--"\
-		-o "-f:|print first entry of random history"\
-		-o "-L:|print last entry of random history"\
-		-o "-i:decimal|print nth entry of random history"\
-		-o "-l:|print number of entries in random history"\
-		-o "-c:|clear random history"\
-		-o "\tor:|--"\
-		-o "-n:decimal|repeat process n times"\
-		-o "--:|delimiter"\
-		-o "files:|for given files and print result"\
-		-o "\tor:|--"\
-		-o "-p:|only print result"\
-		-o "--:|delimiter"\
-		-o "files:|for given files and print result"
+		-l "GNU GPL v3" -n "randomfile" -s $"run a command on a random file" -v "${BSNG_VERSION}" -y "${BSNG_YEAR}"\
+		-o $"command:|command to run for file"\
+		-o $"--:|end of command"\
+		-o $"files:|list of possible files"\
+		-o $"\tor:|--"\
+		-o $"-z command:|command to run for file, append result without space"\
+		-o $"--:|end of command"\
+		-o $"files:|list of possible files"\
+		-o $"\tor:|--"\
+		-o $"-f:|print first entry of random history"\
+		-o $"-L:|print last entry of random history"\
+		-o $"-i:decimal|print nth entry of random history"\
+		-o $"-l:|print number of entries in random history"\
+		-o $"-c:|clear random history"\
+		-o $"\tor:|--"\
+		-o $"-n:decimal|repeat process n times"\
+		-o $"--:|delimiter"\
+		-o $"files:|for given files and print result"\
+		-o $"\tor:|--"\
+		-o $"-p:|only print result"\
+		-o $"--:|delimiter"\
+		-o $"files:|for given files and print result"
 }
 
 case ${1} in
@@ -86,25 +89,25 @@ case ${1} in
 	-f | --first)
 		[[ -f ${HOME}/.randomhistory ]] && \
 			sed -n '1p' "${HOME}"/.randomhistory || \
-			echo "no 'randomfile' history available"
+			echo $"no 'randomfile' history available"
 	;;
 
 	-L | --last)
 		[[ -f ${HOME}/.randomhistory ]] && \
 			sed -n '$p' "${HOME}"/.randomhistory || \
-			echo "no 'randomfile' history available"
+			echo $"no 'randomfile' history available"
 	;;
 
 	-i | --item)
 		[[ -f ${HOME}/.randomhistory ]] && \
 			sed -n "${2}p" "${HOME}"/.randomhistory || \
-			echo "no 'randomfile' history available"
+			echo $"no 'randomfile' history available"
 	;;
 
 	-l | --length)
 		[[ -f ${HOME}/.randomhistory ]] && \
 			wc -l "${HOME}"/.randomhistory | gawk '{print $1}' || \
-			echo "no 'randomfile' history available"
+			echo $"no 'randomfile' history available"
 	;;
 
 	-c | --clear)
@@ -140,3 +143,5 @@ case ${1} in
 	;;
 
 esac
+
+unset TEXTDOMAIN
