remove check_opt

diff --git a/rc/functions/apkdump b/rc/functions/apkdump
--- a/rc/functions/apkdump
+++ b/rc/functions/apkdump
@@ -9,6 +9,12 @@
 #							#
 #########################################################
 
+which aapt &>/dev/null
+if [[ $? != 0 ]]; then
+	echo -e "aapt not found, apkdump won't work."
+	exit 1
+fi
+
 opt=${1}
 shift
 
diff --git a/rc/functions/man2pdf b/rc/functions/man2pdf
--- a/rc/functions/man2pdf
+++ b/rc/functions/man2pdf
@@ -9,7 +9,11 @@
 #							#
 #########################################################
 
-check_opt ps2pdf man2pdf
+which ps2pdf &>/dev/null
+if [[ $? != 0 ]]; then
+	echo -e "ps2pdf not found, man2pdf won't work."
+	exit 1
+fi
 
 case ${1} in
 
diff --git a/rc/functions/movie2gif b/rc/functions/movie2gif
--- a/rc/functions/movie2gif
+++ b/rc/functions/movie2gif
@@ -9,7 +9,11 @@
 #							#
 #########################################################
 
-check_opt ffmpeg movie2gif
+which ffmpeg &>/dev/null
+if [[ $? != 0 ]]; then
+	echo "ffmpeg not found, movie2gif won't work."
+	exit 1
+fi
 
 # by maxwux
 
diff --git a/rc/functions/systemkit b/rc/functions/systemkit
--- a/rc/functions/systemkit
+++ b/rc/functions/systemkit
@@ -12,16 +12,21 @@
 case ${1} in
 
 	battery)
-		check_opt acpi systemkit::battery && (
-			load=$(acpi -b | sed -e "s/.* \([1-9][0-9]*\)%.*/\1/")
-			out="$(acpi -b)"
-			state="$(echo "${out}" | awk '{print $3}')"
-			case ${state} in
-				charging,)	statesign="^" ;;
-				discharging,)	statesign="v" ;;
-				charged,)	statesign="°" ;;
-			esac
-			echo "${statesign}${load}" )
+		which acpi &>/dev/null
+		if [[ $? != 0 ]]; then
+			echo -e "acpi not found, 'systemkit battery' won't work."
+			exit 1
+		fi
+
+		load=$(acpi -b | sed -e "s/.* \([1-9][0-9]*\)%.*/\1/")
+		out="$(acpi -b)"
+		state="$(echo "${out}" | awk '{print $3}')"
+		case ${state} in
+			charging,)	statesign="^" ;;
+			discharging,)	statesign="v" ;;
+			charged,)	statesign="°" ;;
+		esac
+		echo "${statesign}${load}"
 	;;
 
 	cpuload)
@@ -49,8 +54,12 @@ case ${1} in
 	;;
 
 	externalip)
-		check_opt wget systemkit::externalip && \
-			wget -q -O - http://showip.spamt.net/
+		which wget &>/dev/null
+		if [[ $? != 0 ]]; then
+			echo -e "wget not found, 'systemkit externalip' won't work."
+			exit 1
+		fi
+		wget -q -O - http://showip.spamt.net/
 	;;
 
 	internalip)
@@ -136,23 +145,36 @@ case ${1} in
 	;;
 
 	pci)
-		check_opt lspci systemkit::pci && (
+		which lspci &>/dev/null
+		if [[ $? != 0 ]]; then
+			echo -e "lspci not found, 'systemkit lspci' won't work."
+			exit 1
+		fi
 		echo -e "PCI Devices:
-$(lspci -vkmm)\n" )
+$(lspci -vkmm)\n"
 	;;
 
 	usb)
-		check_opt lsusb systemkit::usb && ( 
+		which lsusb &>/dev/null
+		if [[ $? != 0 ]]; then
+			echo -e "lsusb not found, 'systemkit usb' won't work."
+			exit 1
+		fi
 		echo -e "USB Devices:
-$(lsusb -v)\n" )
+$(lsusb -v)\n"
 	;;
 
 	bios)
-		check_opt dmidecode systemkit::bios && (
+		which dmidecode &>/dev/null
+		if [[ $? != 0 ]]; then
+			echo -e "dmidecode not found, 'systemkit bios' won't work."
+			exit 1
+		fi
+
 		if [[ ${EUID} == 0 ]]; then 
 			echo -e "SMBIOS/DMI Info:
 $(dmidecode -q)\n"
-		fi )
+		fi
 	;;
 
 	load1)	LANG=C uptime | sed -e 's/.*average://;s/[[:space:]]//g' | gawk -F , '{print $1}' ;;
