fixup map

diff --git a/rc/functions/map b/rc/functions/map
--- a/rc/functions/map
+++ b/rc/functions/map
@@ -10,7 +10,7 @@
 #########################################################
 
 if [ $# -lt 2 ] || [[ ! "$@" =~ :[[:space:]] ]];then
-	echo "Invalid syntax." >&2; return 1
+	echo "Invalid syntax." >&2; exit 1
 fi
 
 until [[ $1 =~ : ]]; do
