coding style + dependency check: xmlpager

diff --git a/rc/functions/xmlpager b/rc/functions/xmlpager
--- a/rc/functions/xmlpager
+++ b/rc/functions/xmlpager
@@ -9,6 +9,12 @@
 #							#
 #########################################################
 
+which xmlindent &>/dev/null
+if [[ $? != 0 ]]; then
+	echo -e "xmlindent not found, xmlpager won't work."
+	exit 1
+fi
+
 case ${1} in
 
 	-h | --help )
@@ -20,7 +26,7 @@ case ${1} in
 
 	*)
 		xmlindent "${@}" | \
-			awk '{gsub(">",">'`tput bold; tput setf 4`'"); gsub("<","'`tput sgr0`'<"); print;} END {print "'`tput sgr0`'"}' | \
+			awk '{gsub(">",">'$(tput bold; tput setf 4)'"); gsub("<","'$(tput sgr0)'<"); print;} END {print "'$(tput sgr0)'"}' | \
 			less -r
 	;;
 
